spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: usercenter
server:
  tomcat:
    accesslog:
      directory: accesslog
      enabled: true
      prefix: access_log
      suffix: .log
      rotate: true
      file-date-format: .yyyy-MM-dd
      request-attributes-enabled: true
    basedir: user_center_tomcat
  max-http-header-size: 8192